definitions:
  main.Request:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 返回数据
        type: string
      limit:
        description: 返回条数
        type: integer
      msg:
        description: 响应信息
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: api接口测试文档
  title: 调试swagger文档
  version: "1.0"
paths:
  /api/index:
    get:
      description: 返回一个用户列表，可根据查询参数指定
      parameters:
      - description: 返回多少条
        in: query
        name: limit
        type: integer
      - description: 表示多个参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 用户列表
      tags:
      - 用户管理
swagger: "2.0"
