package main

import (
	"net/http"
	_ "page/swag/docs"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	gs "github.com/swaggo/gin-swagger"
)

// docs is generated by Swag CLI, you have to import it.

func index(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"msg": "ok",
	})
}

// @title 这里写标题
// @version 1.0
// @description 这里写描述信息
// @host 这里写接口服务的host
func main() {
	r := gin.Default()
	r.GET("/", index)
	r.GET("/swagger/*any", gs.WrapHandler(swaggerFiles.Handler))
	r.Run()
}
